---
- name: Run nvidia-smi and show output
  hosts: all
  gather_facts: no
  tasks:
    - name: Execute nvidia-smi
      command: nvidia-smi
      register: result
      changed_when: false

    - name: Display output
      debug:
        msg: "{{ result.stdout_lines }}"
