
---
- name: Print gpu usage
  hosts: all
  gather_facts: no

  tasks:
    - name: Run nvidia-smi
      command: nvidia-smi
      register: host_out
      ignore_errors: yes

    - name: Display usage
      debug:
        msg: "{{ inventory_hostname }} -> {{ host_out.stdout | default('NO OUTPUT') }}"
