---
- name: Run nvidia-smi with shell
  hosts: all
  gather_facts: no
  tasks:
    - name: Run nvidia-smi via shell to inherit PATH
      shell: nvidia-smi
      register: result
      changed_when: false
      ignore_errors: yes  # 避免因命令不存在而中断

    - name: Show output or error
      debug:
        msg: |
          stdout: {{ result.stdout_lines | default([]) }}
          stderr: {{ result.stderr | default('') }}
          rc: {{ result.rc }}
